version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev_default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./git-cube-front/git-cube/dist/:/usr/share/nginx/html
    networks:
      - internal_network
      - external_network
    depends_on:
      backend:
        condition: service_healthy

  front-dev:
    build:
      context: git-cube-front
    ports:
      - "3000:3000"
    volumes:
      - ./git-cube-front/git-cube/src/:/app/src
    networks:
      - internal_network

  backend:
    build:
      context: git-cube-backend
    volumes:
      - ./git-cube-backend:/app
    networks:
      - internal_network
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    volumes:
      - ./git-cube-db/data:/var/lib/mysql
      - ./git-cube-db/init:/docker-entrypoint-initdb.d
      - ./git-cube-db/mysql.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - internal_network
    env_file:
      - ./git-cube-db/.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p $$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  internal_network:
    internal: true
  external_network: